version: '2'
name: faucet
services:
    prometheus:
        container_name: prometheus
        image: 'prom/prometheus:v2.48.1'
        user: 'root'
        ports:
            - '9090:9090'
        volumes:
            - './faucet/etc/prometheus:/etc/prometheus'
        links:
            - faucet
            - gauge
    grafana:
        container_name: grafana
        image: 'grafana/grafana:10.2.2'
        user: 'root'
        ports:
            - '3000:3000'
        volumes:
            - './faucet/opt/grafana:/var/lib/grafana'
        links:
            - prometheus
    gauge:
        container_name: gauge
        image: 'faucet/gauge'
        volumes:
            - ./faucet.yaml:/etc/faucet/faucet.yaml
            - ./gauge.yaml:/etc/faucet/gauge.yaml
        ports:
            - 6654:6653
            - 9303:9303
    faucet:
        container_name: faucet
        image: 'faucet/faucet'
        volumes:
            - ./faucet.yaml:/etc/faucet/faucet.yaml
            - ./gauge.yaml:/etc/faucet/gauge.yaml
        ports:
            - 6653:6653
            - 9302:9302
